language: node_js
sudo: required
notifications:
  email: false
node_js:
- '15'
install:
  - npm ci
script:
  - npm run travis:verify
after_success:
- curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
    global:
    - REPO="git@github.com:RedHatInsights/compliance-frontend-build"
    - REPO_DIR="compliance-frontend-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
